site_name: CT/AppSeed Docs
site_description: Official Docs | CT/AppSeed
site_url: https://docs-creativetim.appseed.us/
repo_url: https://github.com/app-generator/docs-creativetim/

markdown_extensions:
  - meta
  - markdown_include.include:
      base_path: docs/common

nav:
- Sections:  
  - 'What Is'                : 'what-is/index.md'   
  - 'How To'                 : 'how-to/index.md'   
  - 'Tutorials'              : 'tutorials/index.md'   
  - 'Starters'               : 'boilerplate-code/index.md'   

- Products:  
  - 'Black Dashboard Django' : 'products/black-dashboard-django/index.md'   
  - 'Argon Dashboard Django' : 'products/argon-dashboard-django/index.md'   
  - 'Material Dashboard Django' : 'products/material-dashboard-django/index.md'   
